### ISSUE TITLE
add a new function - grid alignment

### ISSUE THREAD

**Issue by shikulja** [andryblack/fontbuilder#20]
really need this function, because the only way to correctly align the font, in some games. For example it has done in CBFG.

**Comment by doug65536** [comment]
Can you describe what you mean by "grid alignment"? Do you mean, find the largest character and lay out the image with each character in a cell of that maximum size?

**Comment by doug65536** [comment]
...or do you mean by manually specifying the cell size, horizontally and vertically?

**Comment by shikulja** [comment]
Yes vertically and horizontally, as is done in CBFG.
you need to be able to make the letters on the grid, currently there is no such possibility.

**Comment by shikulja** [comment]
just as there is no manual selection of image size, then only automatic. eg 256x256 512x512, etc.

**Comment by errorx666** [comment]
This would simplify my life a lot, as I wouldn't have to deal with metrics metadata files.  I could simply calculate the offset of the row and column of the desired character.
My use-case is sampling from a font texture in a shader, so not dealing with metadata would be a huge win.
